# Generated by Django 5.2.1 on 2025-05-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('is_threat', models.BooleanField()),
                ('jarm_fingerprint', models.TextField(blank=True, null=True)),
                ('raw_output', models.TextField()),
            ],
        ),
    ]
