# Generated by Django 5.2.1 on 2025-05-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malware_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('ip_address', models.GenericIPAddressField()),
                ('first_seen', models.DateTimeField()),
            ],
        ),
    ]
