# Generated by Django 5.2.1 on 2025-06-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_suspiciousip'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousip',
            name='jarm_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
