# Generated by Django 5.2.1 on 2025-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_suspiciousip_jarm_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('ja4_fingerprint', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='suspiciousip',
            name='ja4_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
