# Generated by Django 5.2.1 on 2025-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_suspiciousip2_suspiciousip_ja4_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousip',
            name='c2_decision',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
